time:2024-12-11T05:31:31.854+0000  filename:local_task_job_runner.py:123  levelname:INFO  err_message:::group::Pre task execution logs
time:2024-12-11T05:31:31.861+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: successful_dag.hello_task manual__2024-12-11T05:31:29.369669+00:00 [queued]>
time:2024-12-11T05:31:31.864+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: successful_dag.hello_task manual__2024-12-11T05:31:29.369669+00:00 [queued]>
time:2024-12-11T05:31:31.865+0000  filename:taskinstance.py:2866  levelname:INFO  err_message:Starting attempt 1 of 2
time:2024-12-11T05:31:31.872+0000  filename:taskinstance.py:2889  levelname:INFO  err_message:Executing <Task(PythonOperator): hello_task> on 2024-12-11 05:31:29.369669+00:00
time:2024-12-11T05:31:31.875+0000  filename:standard_task_runner.py:72  levelname:INFO  err_message:Started process 1969 to run task
time:2024-12-11T05:31:31.878+0000  filename:standard_task_runner.py:104  levelname:INFO  err_message:Running: ['***', 'tasks', 'run', 'successful_dag', 'hello_task', 'manual__2024-12-11T05:31:29.369669+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/success_dag.py', '--cfg-path', '/tmp/tmpft7h48rf']
time:2024-12-11T05:31:31.879+0000  filename:standard_task_runner.py:105  levelname:INFO  err_message:Job 15: Subtask hello_task
time:2024-12-11T05:31:31.907+0000  filename:task_command.py:467  levelname:INFO  err_message:Running <TaskInstance: successful_dag.hello_task manual__2024-12-11T05:31:29.369669+00:00 [running]> on host be4087a9fa6a
time:2024-12-11T05:31:31.951+0000  filename:taskinstance.py:3132  levelname:INFO  err_message:Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='successful_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T05:31:29.369669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T05:31:29.369669+00:00'
time:2024-12-11T05:31:31.951+0000  filename:taskinstance.py:731  levelname:INFO  err_message:::endgroup::
time:2024-12-11T05:31:31.969+0000  filename:python.py:240  levelname:INFO  err_message:Done. Returned value was: Hello world!
time:2024-12-11T05:31:31.982+0000  filename:taskinstance.py:340  levelname:INFO  err_message:::group::Post task execution logs
time:2024-12-11T05:31:31.982+0000  filename:taskinstance.py:352  levelname:INFO  err_message:Marking task as SUCCESS. dag_id=successful_dag, task_id=hello_task, run_id=manual__2024-12-11T05:31:29.369669+00:00, execution_date=20241211T053129, start_date=20241211T053131, end_date=20241211T053131
time:2024-12-11T05:31:32.015+0000  filename:local_task_job_runner.py:266  levelname:INFO  err_message:Task exited with return code 0
time:2024-12-11T05:31:32.022+0000  filename:local_task_job_runner.py:245  levelname:INFO  err_message:::endgroup::
