time:2024-12-06T04:59:23.532+0000  filename:local_task_job_runner.py:123  levelname:INFO  err_message:::group::Pre task execution logs
time:2024-12-06T04:59:23.532+0000  filename:local_task_job_runner.py:123  levelname:INFO  err_message:::group::Pre task execution logs
time:2024-12-06T04:59:23.542+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: successful_dag.hello_task manual__2024-12-06T04:59:20.834731+00:00 [queued]>
time:2024-12-06T04:59:23.543+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: successful_dag.hello_task scheduled__2023-01-01T00:00:00+00:00 [queued]>
time:2024-12-06T04:59:23.547+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: successful_dag.hello_task manual__2024-12-06T04:59:20.834731+00:00 [queued]>
time:2024-12-06T04:59:23.547+0000  filename:taskinstance.py:2866  levelname:INFO  err_message:Starting attempt 1 of 2
time:2024-12-06T04:59:23.547+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: successful_dag.hello_task scheduled__2023-01-01T00:00:00+00:00 [queued]>
time:2024-12-06T04:59:23.547+0000  filename:taskinstance.py:2866  levelname:INFO  err_message:Starting attempt 1 of 2
time:2024-12-06T04:59:23.555+0000  filename:taskinstance.py:2889  levelname:INFO  err_message:Executing <Task(PythonOperator): hello_task> on 2024-12-06 04:59:20.834731+00:00
time:2024-12-06T04:59:23.557+0000  filename:taskinstance.py:2889  levelname:INFO  err_message:Executing <Task(PythonOperator): hello_task> on 2023-01-01 00:00:00+00:00
time:2024-12-06T04:59:23.559+0000  filename:standard_task_runner.py:72  levelname:INFO  err_message:Started process 141 to run task
time:2024-12-06T04:59:23.560+0000  filename:standard_task_runner.py:72  levelname:INFO  err_message:Started process 142 to run task
time:2024-12-06T04:59:23.562+0000  filename:standard_task_runner.py:104  levelname:INFO  err_message:Running: ['***', 'tasks', 'run', 'successful_dag', 'hello_task', 'manual__2024-12-06T04:59:20.834731+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/success_dag.py', '--cfg-path', '/tmp/tmptw856fki']
time:2024-12-06T04:59:23.563+0000  filename:standard_task_runner.py:105  levelname:INFO  err_message:Job 3: Subtask hello_task
time:2024-12-06T04:59:23.562+0000  filename:standard_task_runner.py:104  levelname:INFO  err_message:Running: ['***', 'tasks', 'run', 'successful_dag', 'hello_task', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/success_dag.py', '--cfg-path', '/tmp/tmp161gt1hp']
time:2024-12-06T04:59:23.563+0000  filename:standard_task_runner.py:105  levelname:INFO  err_message:Job 4: Subtask hello_task
time:2024-12-06T04:59:23.591+0000  filename:task_command.py:467  levelname:INFO  err_message:Running <TaskInstance: successful_dag.hello_task scheduled__2023-01-01T00:00:00+00:00 [running]> on host 51331a8f6977
time:2024-12-06T04:59:23.594+0000  filename:task_command.py:467  levelname:INFO  err_message:Running <TaskInstance: successful_dag.hello_task manual__2024-12-06T04:59:20.834731+00:00 [running]> on host 51331a8f6977
time:2024-12-06T04:59:23.644+0000  filename:taskinstance.py:3132  levelname:INFO  err_message:Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='successful_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T04:59:20.834731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T04:59:20.834731+00:00'
time:2024-12-06T04:59:23.645+0000  filename:taskinstance.py:731  levelname:INFO  err_message:::endgroup::
time:2024-12-06T04:59:23.646+0000  filename:taskinstance.py:3132  levelname:INFO  err_message:Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='successful_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
time:2024-12-06T04:59:23.647+0000  filename:taskinstance.py:731  levelname:INFO  err_message:::endgroup::
time:2024-12-06T04:59:23.664+0000  filename:python.py:240  levelname:INFO  err_message:Done. Returned value was: Hello world!
time:2024-12-06T04:59:23.666+0000  filename:python.py:240  levelname:INFO  err_message:Done. Returned value was: Hello world!
time:2024-12-06T04:59:23.676+0000  filename:taskinstance.py:340  levelname:INFO  err_message:::group::Post task execution logs
time:2024-12-06T04:59:23.677+0000  filename:taskinstance.py:352  levelname:INFO  err_message:Marking task as SUCCESS. dag_id=successful_dag, task_id=hello_task, run_id=manual__2024-12-06T04:59:20.834731+00:00, execution_date=20241206T045920, start_date=20241206T045923, end_date=20241206T045923
time:2024-12-06T04:59:23.679+0000  filename:taskinstance.py:340  levelname:INFO  err_message:::group::Post task execution logs
time:2024-12-06T04:59:23.679+0000  filename:taskinstance.py:352  levelname:INFO  err_message:Marking task as SUCCESS. dag_id=successful_dag, task_id=hello_task, run_id=scheduled__2023-01-01T00:00:00+00:00, execution_date=20230101T000000, start_date=20241206T045923, end_date=20241206T045923
time:2024-12-06T04:59:23.699+0000  filename:local_task_job_runner.py:266  levelname:INFO  err_message:Task exited with return code 0
time:2024-12-06T04:59:23.706+0000  filename:local_task_job_runner.py:266  levelname:INFO  err_message:Task exited with return code 0
time:2024-12-06T04:59:23.708+0000  filename:taskinstance.py:3895  levelname:INFO  err_message:0 downstream tasks scheduled from follow-on schedule check
time:2024-12-06T04:59:23.712+0000  filename:local_task_job_runner.py:245  levelname:INFO  err_message:::endgroup::
time:2024-12-06T04:59:23.722+0000  filename:taskinstance.py:3895  levelname:INFO  err_message:0 downstream tasks scheduled from follow-on schedule check
time:2024-12-06T04:59:23.726+0000  filename:local_task_job_runner.py:245  levelname:INFO  err_message:::endgroup::
