time:2024-12-05T01:54:46.146+0000  filename:local_task_job_runner.py:123  levelname:INFO  err_message:::group::Pre task execution logs
time:2024-12-05T01:54:46.156+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: successful_dag.hello_task manual__2024-12-05T01:54:43.880189+00:00 [queued]>
time:2024-12-05T01:54:46.160+0000  filename:taskinstance.py:2613  levelname:INFO  err_message:Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: successful_dag.hello_task manual__2024-12-05T01:54:43.880189+00:00 [queued]>
time:2024-12-05T01:54:46.160+0000  filename:taskinstance.py:2866  levelname:INFO  err_message:Starting attempt 1 of 2
time:2024-12-05T01:54:46.166+0000  filename:taskinstance.py:2889  levelname:INFO  err_message:Executing <Task(PythonOperator): hello_task> on 2024-12-05 01:54:43.880189+00:00
time:2024-12-05T01:54:46.169+0000  filename:standard_task_runner.py:72  levelname:INFO  err_message:Started process 72459 to run task
time:2024-12-05T01:54:46.171+0000  filename:standard_task_runner.py:104  levelname:INFO  err_message:Running: ['***', 'tasks', 'run', 'successful_dag', 'hello_task', 'manual__2024-12-05T01:54:43.880189+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/success_dag.py', '--cfg-path', '/tmp/tmpox87qzp6']
time:2024-12-05T01:54:46.171+0000  filename:standard_task_runner.py:105  levelname:INFO  err_message:Job 238: Subtask hello_task
time:2024-12-05T01:54:46.194+0000  filename:task_command.py:467  levelname:INFO  err_message:Running <TaskInstance: successful_dag.hello_task manual__2024-12-05T01:54:43.880189+00:00 [running]> on host 88bd5cc03d91
time:2024-12-05T01:54:46.229+0000  filename:taskinstance.py:3132  levelname:INFO  err_message:Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='successful_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T01:54:43.880189+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T01:54:43.880189+00:00'
time:2024-12-05T01:54:46.230+0000  filename:taskinstance.py:731  levelname:INFO  err_message:::endgroup::
time:2024-12-05T01:54:46.236+0000  filename:python.py:240  levelname:INFO  err_message:Done. Returned value was: Hello world!
time:2024-12-05T01:54:46.246+0000  filename:taskinstance.py:340  levelname:INFO  err_message:::group::Post task execution logs
time:2024-12-05T01:54:46.246+0000  filename:taskinstance.py:352  levelname:INFO  err_message:Marking task as SUCCESS. dag_id=successful_dag, task_id=hello_task, run_id=manual__2024-12-05T01:54:43.880189+00:00, execution_date=20241205T015443, start_date=20241205T015446, end_date=20241205T015446
time:2024-12-05T01:54:46.271+0000  filename:local_task_job_runner.py:266  levelname:INFO  err_message:Task exited with return code 0
time:2024-12-05T01:54:46.280+0000  filename:taskinstance.py:3895  levelname:INFO  err_message:0 downstream tasks scheduled from follow-on schedule check
time:2024-12-05T01:54:46.281+0000  filename:local_task_job_runner.py:245  levelname:INFO  err_message:::endgroup::
